require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
use_frameworks!

target 'PanoRtcExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

      pod 'panortc-react-native-sdk', :path => '../..'
      
      target 'PanoRtcExample-Screen' do
        platform :ios, '11.0'
        use_frameworks!
        pod 'PanoRtc_iOS/ReplayKitExt'
      end
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!('Flipper' => '0.74.0')
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end
